title: Tom's Wonderland
author: Tom WU
email: xiviwo@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  This my blog about my work and life, tell what you think with {{ site.email }}
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: /

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

remote_theme: 
permalink: /posts/:title/
texture:
  title: Tom's Wonderland
  tagline: Devops. Engineer
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false
  disqus_shortname: games

  # generate social links in footer
  social_links:
    twitter: xiviwo
    github:  xiviwo
    linkedIn: xiviwo
    rss: rss
 
  navigation:
    - title: My Work
      url: "/my-work"
    - title: Resume
      url: "/resume"
# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed